"""
IntegrationAgent — step 5 in the 8-agent pipeline.

Connects the frontend to the backend generated by the CoderAgent and designed by
the UIUXAgent.  Produces:
  - `src/services/api.js`         — fully-typed API client with interceptors
  - `src/context/AuthContext.jsx` — auth context with login / register / logout
  - `src/hooks/useApi.js`         — custom hook handling loading / error / data
  - `src/hooks/useAuth.js`        — sugar over AuthContext

Generated files are injected into `state.generated_files` and written to disk so
they stream straight into the frontend FILES panel.

The agent also writes a `INTEGRATION_GUIDE.md` walkthrough that explains how the
layers connect end-to-end.
"""
from __future__ import annotations

import os
import re

from agent_factory.core.base_agent import BaseAgent
from agent_factory.core.state import PipelineState


# ── System prompt ─────────────────────────────────────────────────────────────

INTEGRATION_SYSTEM = """\
You are a Staff-level Full-Stack Engineer.  Your job is to produce the complete
integration layer that glues the frontend to the backend.

You MUST generate these files, fully implemented, production-ready:

1. `src/services/api.js`
   - Axios (or fetch) wrapper with a configurable BASE_URL from VITE_API_URL / REACT_APP_API_URL
   - Request interceptor adds Authorization: Bearer <token> from localStorage
   - Response interceptor handles 401 → logout + redirect
   - Named exports for every endpoint listed in the API contracts

2. `src/context/AuthContext.jsx`
   - React Context holding { user, token, isAuthenticated, loading }
   - Methods: login(email, password), register(...), logout()
   - Persists token in localStorage
   - Fetches current user on mount if token present

3. `src/hooks/useApi.js`
   - Generic hook: `useApi(apiFn, deps)` → { data, loading, error, refetch }
   - Handles race conditions (abort stale requests)

4. `src/hooks/useAuth.js`
   - Thin sugar over AuthContext: `const { user, login, logout } = useAuth()`
   - Throws if used outside provider

5. `src/components/ProtectedRoute.jsx`
   - Wraps children; redirects to /login if not authenticated
   - Shows loading state while auth status is resolving

## STRICT OUTPUT CONTRACT

For EVERY file use this EXACT marker so our parser extracts it:

FILE: /frontend/src/services/api.js
```javascript
// complete code — no truncation
```

Rules:
- NO placeholders, NO "TODO", NO "..."
- Fully type-safe if TypeScript is the target stack
- Graceful error handling — never crash on network failure
- Add JSDoc on every public function
- Use modern React (hooks, functional components)
- Never hard-code credentials — read from env

After the FILE blocks, output a section starting with exactly:

INTEGRATION NOTES:
  - [short bullet 1]
  - [short bullet 2]

These notes become part of the integration report.  No other prose.
"""


# ── Agent implementation ───────────────────────────────────────────────────────

class IntegrationAgent(BaseAgent):
    """
    Generates the frontend ⇄ backend integration layer.
    """

    def __init__(self, llm_client) -> None:
        super().__init__("IntegrationAgent", llm_client)

    def run(self, state: PipelineState) -> PipelineState:
        state.set_agent(self.name)
        self.log("Wiring the integration layer (api.js, AuthContext, hooks)...")

        # Summarise API contracts + stack for the LLM
        contracts_brief = self._summarise_contracts(state.api_contracts or [])
        stack = ", ".join(state.tech_stack[:10]) if state.tech_stack else "React + Node.js"

        user_prompt = (
            f"PROJECT: {state.project_name or 'Unnamed Project'}\n"
            f"TECH STACK: {stack}\n\n"
            f"REQUIREMENT:\n{state.raw_requirement}\n\n"
            f"API CONTRACTS (from ArchitectAgent):\n{contracts_brief or '(none — infer reasonable REST endpoints)'}\n\n"
            "Generate the complete integration layer now."
        )

        response = self.call_llm(
            prompt=user_prompt,
            system=INTEGRATION_SYSTEM,
            use_cache=False,
        )

        files, notes = self._parse(response)
        self.log(f"Extracted {len(files)} integration files + {len(notes)} notes.")

        # Inject into shared state for streaming
        for path, content in files.items():
            state.generated_files[path] = content
            state.integration_files.append(path)

        # Persist on disk if we have an output folder
        output_dir = state.output_path
        if output_dir:
            for rel_path, content in files.items():
                safe = rel_path.lstrip("/\\")
                dest = os.path.join(output_dir, safe)
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                with open(dest, "w", encoding="utf-8") as fh:
                    fh.write(content)

        # Build integration guide
        guide = self._build_guide(files, notes)
        state.integration_notes = notes
        state.integration_guide = guide
        state.generated_files["INTEGRATION_GUIDE.md"] = guide
        if output_dir:
            with open(os.path.join(output_dir, "INTEGRATION_GUIDE.md"), "w", encoding="utf-8") as fh:
                fh.write(guide)

        self.log(f"Integration layer ready — {len(files)} files, guide saved.")
        return state

    # ── helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _summarise_contracts(contracts: list[dict]) -> str:
        if not contracts:
            return ""
        lines: list[str] = []
        for c in contracts[:25]:
            method = c.get("method", "")
            path   = c.get("path",   "")
            desc   = c.get("description", c.get("purpose", ""))
            lines.append(f"- {method.upper():6} {path:30}  {desc}")
        return "\n".join(lines)

    @staticmethod
    def _parse(text: str) -> tuple[dict[str, str], list[str]]:
        # files
        files: dict[str, str] = {}
        pattern = re.compile(
            r"FILE:\s*([^\n]+?)\s*\n```[a-zA-Z0-9+-]*\s*\n(.*?)\n```",
            re.DOTALL,
        )
        for match in pattern.finditer(text):
            raw_path = match.group(1).strip().strip("`").strip()
            code     = match.group(2).rstrip()
            path = raw_path.replace("\\", "/").lstrip("/")
            if path:
                files[path] = code

        # notes
        notes: list[str] = []
        marker = "INTEGRATION NOTES:"
        if marker in text:
            tail = text.split(marker, 1)[1]
            for line in tail.splitlines():
                stripped = line.strip().lstrip("-•*").strip()
                if stripped:
                    notes.append(stripped)
                if len(notes) >= 20:
                    break
        return files, notes

    @staticmethod
    def _build_guide(files: dict[str, str], notes: list[str]) -> str:
        lines = [
            "# Integration Guide",
            "",
            "This document explains how the frontend and backend are wired together.",
            "",
            "## Generated integration files",
            "",
        ]
        for path in sorted(files.keys()):
            lines.append(f"- `{path}`")
        lines.append("")
        if notes:
            lines.append("## Integration notes")
            lines.append("")
            for n in notes:
                lines.append(f"- {n}")
            lines.append("")
        lines.append("## Typical flows")
        lines.append("")
        lines.append("### 1. User login")
        lines.append("`LoginPage` → `useAuth().login(email, password)` → `api.js POST /auth/login` → "
                     "token stored in `localStorage` → `AuthContext` updates → protected routes unlock.")
        lines.append("")
        lines.append("### 2. Protected data fetch")
        lines.append("`DashboardPage` → `useApi(api.getThings)` → interceptor adds `Authorization` "
                     "header → backend validates JWT → data returned → hook surfaces `{ data, loading, error }`.")
        lines.append("")
        lines.append("### 3. Token expiry")
        lines.append("Backend returns `401` → response interceptor in `api.js` clears token and "
                     "redirects to `/login`.")
        lines.append("")
        return "\n".join(lines)
